// Emoji dataset (generated by scripts/build-emoji.mjs), loaded lazily the
// first time a picker or autocomplete needs it.
import { settings } from "../../store/settings";

/** [char, group, shortcodes (space-separated), keywords ("|"-separated), skins?] */
type Row = [string, number, string, string, string[]?];

export interface Emoji {
  char: string;
  group: number;
  codes: string[];
  keywords: string;
  skins?: string[];
}

let loaded: Emoji[] | null = null;
let loading: Promise<Emoji[]> | null = null;
const byCode = new Map<string, Emoji>();

export function loadEmoji(): Promise<Emoji[]> {
  if (loaded) return Promise.resolve(loaded);
  loading ??= import("./data.json").then((m) => {
    const rows = (m.default as unknown as Row[]) ?? [];
    loaded = rows.map(([char, group, codes, keywords, skins]) => ({ char, group, codes: codes ? codes.split(" ") : [], keywords, skins }));
    for (const e of loaded) for (const c of e.codes) if (!byCode.has(c)) byCode.set(c, e);
    return loaded;
  });
  return loading;
}

export const emojiLoaded = () => loaded;

export function withSkin(e: Emoji, tone = settings().skinTone): string {
  return tone > 0 && e.skins?.[tone - 1] ? e.skins[tone - 1] : e.char;
}

export function findByCode(code: string): Emoji | undefined {
  return byCode.get(code.toLowerCase());
}

/** Ranked search: exact shortcode > shortcode prefix > keyword prefix > contains. */
export function searchEmoji(query: string, limit = 60): Emoji[] {
  if (!loaded) return [];
  const q = query.trim().toLowerCase().replace(/ё/g, "е").replace(/^:|:$/g, "");
  if (!q) return [];
  const scored: { e: Emoji; s: number }[] = [];
  for (const e of loaded) {
    let s = 0;
    if (e.codes.includes(q)) s = 100;
    else if (e.codes.some((c) => c.startsWith(q))) s = 80;
    else {
      const words = e.keywords.split("|");
      if (words.some((w) => w === q)) s = 70;
      else if (words.some((w) => w.startsWith(q) || w.split(" ").some((p) => p.startsWith(q)))) s = 50;
      else if (q.length > 2 && e.keywords.includes(q)) s = 20;
    }
    if (s) scored.push({ e, s });
  }
  return scored
    .sort((a, b) => b.s - a.s)
    .slice(0, limit)
    .map((x) => x.e);
}

export function recordRecent(key: string) {
  const s = settings();
  const next = [key, ...s.recentEmoji.filter((k) => k !== key)].slice(0, 32);
  s.setSynced({ recentEmoji: next });
}
